{"name": "test_name", "status": "failed", "statusDetails": {"message": "AssertionError: assert not 'persons name is alex' == 'persons name is alex'\n    persons name is alex", "trace": "self = <tests.google.test_dummy.TestPerson object at 0x0000026CF151ADD0>\n\n    def test_name(self) -> None:\n        person.name = 'alex'\n>       assert not person.get_data() == 'persons name is alex'\nE       AssertionError: assert not 'persons name is alex' == 'persons name is alex'\nE           persons name is alex\n\n..\\..\\..\\tests\\google\\test_dummy.py:28: AssertionError"}, "start": 1677627283129, "stop": 1677627283129, "uuid": "a0dd7748-2232-4b1e-b7ad-91e39d114d30", "historyId": "fce9cbe8ff1a424e195a63a7349514a6", "testCaseId": "7a1cc6499cbaa70fdb80eca6a8b8a95f", "fullName": "tests.google.test_dummy.TestPerson#test_name", "labels": [{"name": "parentSuite", "value": "tests.google"}, {"name": "suite", "value": "test_dummy"}, {"name": "subSuite", "value": "TestPerson"}, {"name": "host", "value": "LAPTOP-6VHLMB5Q"}, {"name": "thread", "value": "24292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.google.test_dummy"}]}