{"name": "test_image_compare", "status": "broken", "statusDetails": {"message": "TypeError: 'NoneType' object is not callable", "trace": "self = <test_intro_page.TestIntroPage object at 0x000002EAFFCA3940>\n\n    def test_image_compare(self) -> None:\n        image_compare = ImageCompare()\n>       image_compare.execute()\n\ngoogle\\test_intro_page.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\core\\tools\\image_compare\\image_compare_executor.py:15: in execute\n    result = self.compare_images(original_image_path=data.original_image_path,\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = ImageCompare()\noriginal_image_path = 'C:\\\\Users\\\\evgenyp\\\\Desktop\\\\1.png'\nactual_image_path = 'C:\\\\Users\\\\evgenyp\\\\Desktop\\\\2.png'\nimage_resolution = [800, 800]\n\n    def compare_images(self,\n                       original_image_path: str,\n                       actual_image_path: str,\n                       image_resolution: list[int, int]) -> float:\n    \n        _before = cv2.imread(original_image_path)\n        _after = cv2.imread(actual_image_path)\n>       self.log(level=logging.DEBUG, text=f\" Test: {__name__}, load and resize images\")\nE       TypeError: 'NoneType' object is not callable\n\n..\\core\\tools\\image_compare\\image_compare.py:30: TypeError"}, "start": 1687095005492, "stop": 1687095005495, "uuid": "578286f4-1c98-45cd-932b-e1ebbdd8c41c", "historyId": "a32b421f81a95bc83a4e08aa1456be13", "testCaseId": "6c71dd5c092a8545aea39a4dc794c225", "fullName": "google.test_intro_page.TestIntroPage#test_image_compare", "labels": [{"name": "parentSuite", "value": "google"}, {"name": "suite", "value": "test_intro_page"}, {"name": "subSuite", "value": "TestIntroPage"}, {"name": "host", "value": "IL-EVGENYP-LP"}, {"name": "thread", "value": "42088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "google.test_intro_page"}]}